import { c, blue, indigo } from "./index";
// import { c } from "./dist/index.mjs";

// console.log("-> ", c("blue", 0));
// console.log("-> ", c("blue", 50));
// console.log("-> ", c("blue", 500));
// console.log("-> ", c("blue", 900));
// console.log("-> ", c("green", 200));
// console.log("-> ", c("blue", 500, "csshsl"));
// console.log("-> ", c("blue", 900, "csshsl"));
// console.log("-> ", c("blue", 200, "csshsl"));
// console.log("-> ", c("blue", 500, "rgba"));
// console.log("-> ", c("blue", 900, "rgba"));
// console.log("-> ", c("blue", 200, "rgba"));
// console.log("-> ", c.blue, "");
// console.log("-> ", c(c.blue, 777), "");

// console.log("-> ", { colors_array_of_names }, "");

// console.log(c("gray", 650));
// console.log(c("blue", 777));
// console.log(c("blue", 777, "hex"));
// console.log(c("blue", 777, "rgb"));
// console.log(c("blue", 777, "rgba"));
// console.log(c("blue", 777, "hsl"));
// console.log(c("blue", 777, "hsv"));
// console.log(c("blue", 777, "hsi"));
// console.log(c("blue", 777, "lab"));
// console.log(c("blue", 777, "lch"));
// console.log(c("blue", 777, "hcl"));
// console.log(c("blue", 777, "oklab"));
// console.log(c("blue", 777, "oklch"));
// console.log(c("blue", 777, "cssrgb"));
// console.log(c("blue", 777, "csshsl"));
// console.log(c("blue", 777, "csslab"));
// console.log(c("blue", 777, "csslch"));
// console.log(c("blue", 777, "cssoklab"));
// console.log(c("blue", 777, "cssoklch"));
console.log(c.blue(550));
console.log(c.trueGray(625));
// c.blue(500);
